# Generated by Django 3.1.5 on 2021-11-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='thinkvision',
            fields=[
                ('device_id', models.TextField(max_length=69, primary_key=True, serialize=False)),
                ('slot1', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('slot2', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
            ],
        ),
    ]
